package HelloWorld;


/**
* HelloWorld/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* domingo 20 de marzo de 2022 20H36' CET
*/

public interface HelloOperations 
{

  //
  String hello_world ();
} // interface HelloOperations
